spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: "eastpeople@clinomics.co.kr"
    password: "eastman1"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        mime: UTF-8
        transport:
          protocol: smtp
  datasource:
    initialization-mode: always
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
datasource:
  lims:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.0.201:13306/lims_v2?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: clinomics
    password: uiop7890
  pdf:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.0.201:13306/lims_v2?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: clinomics
    password: uiop7890
lims:
  filePath: /BiO/Serve/lims_v2
  celFilePath: /BiO/Serve/lims_v2/celFiles
  workspacePath : /BiO/Serve/lims_v2/workspace
  apmraChipPath : /BiO/Research/Cel2GSSInput/Script/runAnalysis_GSK.py
  customChipPath : /BiO/Research/Cel2GSSInput/Script/runAnalysis.py
externalApi: 
  url: https://api.genosolutiony.com/getMarker.php
  tokenName: apiKey
  token: $2y$10$8FzBfexBXEJa7PYaERjLvOk3zGgCSiAyTWiNqsjWktfcvuoAH/fKq
titan:
  filePath: D:/BiO/Serve/lims_v2/titan
  ftp:
    address: 192.168.0.238
    port: 21
    username: AFFXUSER
    password: affxpd
rest:
  http:
    auth-token-header-name: limsApiKey
    auth-token: fyhwp9e48fuq90p348yhtg09pq3874yhgt
logging:
  file: /BiO/Serve/lims_v2/logs/lims_v2.log
server:
  port: 9095