spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: "info@clinomics.co.kr"
    password: "@1q2w3e4r@"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        mime: UTF-8
        transport:
          protocol: smtp
  datasource:
    initialization-mode: always
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
management:
  endpoint:
    logfile:
      external-file: /BiO/Serve/lims_v2/logs/lims_v2.log
  endpoints:
    web:
      exposure:
        include: "*"
datasource:
  lims:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/lims_v2?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 7890uiop
  pdf:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/lims_v2?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 7890uiop
lims:
  filePath: /BiO/Serve/lims_v2
  celFilePath: /BiO/Serve/lims_v2/celFiles
  workspacePath : /BiO/Serve/lims_v2/workspace
  apmraChipPath : /BiO/Research/Cel2GSSInput/Script/runAnalysis_GSK.py
  customChipPath : /BiO/Research/Cel2GSSInput/Script/runAnalysis.py
externalApi: 
  url: https://api.genosolutiony.com/etc/
  tokenName: apiKey
  token: Sn4Wy4nlqmGEytAx5SkBXdhAp1LKYXXapc1hb6FG
titan:
  filePath: /BiO/Serve/lims_v2/titan
  ftp:
    address: 192.168.0.238
    port: 21
    username: AFFXUSER
    password: affxpd
rest:
  http:
    auth-token-header-name: limsApiKey
    auth-token: askdfji1294iksvn09230985kslkfjhet09239iu2052u90523knzcxmlvn
logging:
  file: /BiO/Serve/lims_v2/logs/lims_v2.log
server:
  port: 8080
  servlet:
    session:
      timeout: 1800